DROP TABLE CONEXAO CASCADE CONSTRAINTS;
DROP TABLE RESULTADO CASCADE CONSTRAINTS;
DROP TABLE BLOCO CASCADE CONSTRAINTS;
DROP TABLE PROJETO CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;

-- TABELA: USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO   NUMBER,
    NOME         VARCHAR2(100) NOT NULL,
    EMAIL        VARCHAR2(100) UNIQUE NOT NULL,
    SENHA        VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_USUARIO
BEFORE INSERT ON USUARIO
FOR EACH ROW
WHEN (NEW.ID_USUARIO IS NULL)
BEGIN
    SELECT SEQ_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
END;
/


-- TABELA: PROJETO
CREATE TABLE PROJETO (
    ID_PROJETO   NUMBER,
    NOME         VARCHAR2(100) NOT NULL,
    DESCRICAO    VARCHAR2(255),
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    ID_USUARIO   NUMBER NOT NULL,
    CONSTRAINT PK_PROJETO PRIMARY KEY (ID_PROJETO),
    CONSTRAINT FK_PROJETO_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIO (ID_USUARIO)
        ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PROJETO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PROJETO
BEFORE INSERT ON PROJETO
FOR EACH ROW
WHEN (NEW.ID_PROJETO IS NULL)
BEGIN
    SELECT SEQ_PROJETO.NEXTVAL INTO :NEW.ID_PROJETO FROM DUAL;
END;
/


-- TABELA: BLOCO
CREATE TABLE BLOCO (
    ID_BLOCO     NUMBER,
    TIPO         VARCHAR2(50) NOT NULL,
    PARAMETROS   VARCHAR2(255),
    POSICAO_X    FLOAT,
    POSICAO_Y    FLOAT,
    ID_PROJETO   NUMBER NOT NULL,
    CONSTRAINT PK_BLOCO PRIMARY KEY (ID_BLOCO),
    CONSTRAINT FK_BLOCO_PROJETO FOREIGN KEY (ID_PROJETO)
        REFERENCES PROJETO (ID_PROJETO)
        ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_BLOCO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_BLOCO
BEFORE INSERT ON BLOCO
FOR EACH ROW
WHEN (NEW.ID_BLOCO IS NULL)
BEGIN
    SELECT SEQ_BLOCO.NEXTVAL INTO :NEW.ID_BLOCO FROM DUAL;
END;
/


-- TABELA: CONEXAO
CREATE TABLE CONEXAO (
    ID_CONEXAO     NUMBER,
    ID_ORIGEM      NUMBER NOT NULL,
    PORTA_ORIGEM   VARCHAR2(50),
    ID_DESTINO     NUMBER NOT NULL,
    PORTA_DESTINO  VARCHAR2(50),
    CONSTRAINT PK_CONEXAO PRIMARY KEY (ID_CONEXAO),
    CONSTRAINT FK_CONEXAO_ORIGEM FOREIGN KEY (ID_ORIGEM)
        REFERENCES BLOCO (ID_BLOCO)
        ON DELETE CASCADE,
    CONSTRAINT FK_CONEXAO_DESTINO FOREIGN KEY (ID_DESTINO)
        REFERENCES BLOCO (ID_BLOCO)
        ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_CONEXAO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_CONEXAO
BEFORE INSERT ON CONEXAO
FOR EACH ROW
WHEN (NEW.ID_CONEXAO IS NULL)
BEGIN
    SELECT SEQ_CONEXAO.NEXTVAL INTO :NEW.ID_CONEXAO FROM DUAL;
END;
/


-- TABELA: RESULTADO
CREATE TABLE RESULTADO (
    ID_RESULTADO   NUMBER,
    ID_PROJETO     NUMBER NOT NULL,
    TEMPO          FLOAT NOT NULL,
    VALOR          FLOAT NOT NULL,
    CONSTRAINT PK_RESULTADO PRIMARY KEY (ID_RESULTADO),
    CONSTRAINT FK_RESULTADO_PROJETO FOREIGN KEY (ID_PROJETO)
        REFERENCES PROJETO (ID_PROJETO)
        ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_RESULTADO START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_RESULTADO
BEFORE INSERT ON RESULTADO
FOR EACH ROW
WHEN (NEW.ID_RESULTADO IS NULL)
BEGIN
    SELECT SEQ_RESULTADO.NEXTVAL INTO :NEW.ID_RESULTADO FROM DUAL;
END;
/

COMMIT;
